### ISSUE TITLE
大佬能否支持自定义Host和Referer

### ISSUE THREAD

**Issue by goxofy** [Yongke/aerproxy#2]
比如一台服务器上通过nginx部署了2个网站，如果能够支持自定义header里的host的话，那么就能实现这个

```
env_variables:
 PROXY_PASS_HOST_PORT: '111.222.333.444:1234'
 PROXY_PASS_SCHEME: 'https'
 PROXY PASS_HOST: 'abc.com'
```

这样可以实现一个IP地址反代多个网站，后端nginx根据host转发到不同的源站

**Comment by Yongke** [comment]
完全理解你的需求哈，其实我也想实现透传终端用户的referer和host的。
但是免费版appengine使用的urlfetch做不到透传host... 收费版的可以走tcp reverse proxy，是可以的

这个我再研究下

**Comment by Yongke** [comment]
确定Host header没法透传, 免费版appengine的限制

**Comment by goxofy** [comment]
Thanks!
